dataset_paths:
  - '/home/zhaoyixiu/ISR_project/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToCab/mg/2024-05-04-22-12-27_and_2024-05-07-07-39-33/demo_gentex_im128_randcams.hdf5'

camera_names:
  - robot0_agentview_left_image
  - robot0_agentview_right_image
  - robot0_eye_in_hand_image

lan_instructions:
  - null