dataset_paths:
  - '/home/zhaoyixiu/ISR_project/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToCab/2024-04-24/demo_gentex_im128_randcams.hdf5'
  - '/home/zhaoyixiu/ISR_project/robocasa/datasets/v0.1/single_stage/kitchen_pnp/PnPCounterToMicrowave/2024-04-27/demo_gentex_im128_randcams.hdf5'

camera_names:
  - robot0_agentview_left_image

lan_instructions:
  - null
  - null